### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by tarik02** [Tarik02/laravel-blade-js#1]
Roadmap:
 - [x] Use only async API
 - [x] Use TypeScript
 - [x] Remake compiler (use tokenizer & parser instead of State Machine)
   - [x] Make tokenizer
   - [x] Make parser
   - [x] Make new code generator
 - [x] Implement built-in functions
   - [x] Condition blocks
   - [x] Loop blocks
   - [x] Layout constructions
     - [x] extends
     - [x] include
     - [x] stack, push
   - [x] Components and slots
 - [x] Custom template extension
 - [x] Integration with tools
   - [x] webpack loader
 - [ ] Tests
 - [x] Split compiler and runtime into separate packages
 - [ ] Fix issue with accounting '\n' before and after function (this produces many extra empty lines)

**Comment by cossssmin** [comment]
Really looking forward to this! 

Will you please also consider [Components & Slots](https://laravel.com/docs/5.7/blade#components-and-slots) for the "Layout constructions" task? I find that missing in most JS templating languages, it would be extremely useful :)
