### ISSUE TITLE
How can it be used with: app.set('view engine', 'bjs')

### ISSUE THREAD

**Issue by MontejoJorge** [Tarik02/laravel-blade-js#18]
How can i use this view engine with express to call `res.render`?

**Comment by tarik02** [comment]
It is not actually compatible with express's template engine interface. Actually you can write a shim between express and this library.

**Comment by MontejoJorge** [comment]
I might give it a try, because I love blade as a template language, if I get something would you like me to make a pull request?

**Comment by tarik02** [comment]
> I might give it a try, because I love blade as a template language, if I get something would you like me to make a pull request?

If you will make a pull request, I would be happy to merge it
