### ISSUE TITLE
Feature request: custom extension for template files.

### ISSUE THREAD

**Issue by matejsvajger** [Tarik02/laravel-blade-js#2]
Thank you for this awesome package!
Excited that I can use now blade style syntax and template inheritance in my static templates :-)

It would be really cool if it would be possible to pass in a custom file extension into renderer config.

i.e.: instead of `.bjs` i would prefer to have `.blade.html`

```js
BladeRenderer.set({ extension: '.blade.html', ...config});
```

**Comment by tarik02** [comment]
Will be fixed by #1
