### ISSUE TITLE
Bug: templates in nested folders fail rendering when writing cache files

### ISSUE THREAD

**Issue by matejsvajger** [Tarik02/laravel-blade-js#3]
When having a partial or parent in a nested folder writing cache file will fail due to missing subfolder in the cache folder.

i.e having:
```blade
{{-- views/index.bjs --}}
@extens('layouts.app')
@section('content')
  <h1>Welcome</h2>
@endsection
```
`cacheName` for __app.bjs__ will be `this._config.cache + '/layouts/app.cache.js` where the __layouts__ folder does not exist and crashes the process
https://github.com/Tarik02/laravel-blade-js/blob/81e45b5764163626ae6844ecc0677397fc77827f/Renderer.js#L507

Also having `config.cacheEnabled = false` would be better to skip this cache file generation altogether. Currently the cache files are generated independent of this option.

I was trying to make a laravel-mix plugin and currently I need to generate the cache folder structure before rendering the templates:

```js
    glob.sync(`${srcDir}/**/*.bjs`)
        .map(file => new File(file))
        .map(file => file.base().replace(srcDir, cacheDir))
        .map(path => mkdirp(path))
```

**Comment by tarik02** [comment]
Will be fixed by #1
