### ISSUE TITLE
Loader option for rendered output

### ISSUE THREAD

**Issue by ghost** [Tarik02/laravel-blade-js#7]
Is it possible to add an option so the webpack loader does the rendering too via the runtime?

**Comment by tarik02** [comment]
Rendering is always done in runtime. The Webpack loader only compiles templates to functions using `bladejs-compiler`. If you meant template compiling, then no. If you want to compile templates at runtime, you actually don't even need the Webpack loader, it is enough to use `raw-loader` and compile the templates (but I don't recommend to do this).

**Comment by committomaster** [comment]
Say I want to use webpack to statically generate HTML from Blade templates at build time. How may I achieve this with the loader?

**Comment by tarik02** [comment]
The loader is not able to do this. Seems, you need to create a custom loader which can do this.

**Comment by committomaster** [comment]
I figured, but thought maybe it could be added as a feature to this loader. Haven't written a webpack loader before but I'll give it a try. Thank you!

**Comment by tarik02** [comment]
I think, there should be separate loaders for such things, because they're really different. Have a good luck with writing a loader.

**Comment by ghost** [comment]
Yes, I understand. I gave it a try [here](https://github.com/mfarhadpur/blade-html-loader/blob/develop/lib/index.js), but I'm getting an error `TypeError: template.call is not a function`. I'd appreciate it if you could take a look, if you have the time at all.

**Comment by tarik02** [comment]
Take a look at this line of the example: https://github.com/Tarik02/laravel-blade-js/blob/master/examples/express/src/index.ts#L27. There's `new Function(...`, this is mandatory.

**Comment by ghost** [comment]
Yes, that was the issue. Thanks so much for your help and this library.

**Comment by tarik02** [comment]
:). Can this issue be closed?
